"""new db

Revision ID: 43355abbf8fb
Revises: 
Create Date: 2018-05-09 13:32:47.983424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43355abbf8fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.Column('id_supergroup', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('comfort',
    sa.Column('id_comfort', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Socket', 'WelcomeTourists', 'ForChildren', 'AnimalAccess', 'RentBikes', 'Polygraph', 'Ramp', 'SpecialToilet', 'SpecialService', name='comfortenum'), nullable=True),
    sa.PrimaryKeyConstraint('id_comfort')
    )
    op.create_table('payment_method',
    sa.Column('id_payment_method', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DebitCard', 'CreditCard', 'ElectronicPayment', name='paymentmethodenum'), nullable=True),
    sa.PrimaryKeyConstraint('id_payment_method')
    )
    op.create_table('place',
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=350), nullable=True),
    sa.Column('website', sa.String(length=70), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_place')
    )
    op.create_table('time_table',
    sa.Column('id_timetable', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id_timetable')
    )
    op.create_table('category_place',
    sa.Column('id_category_place', sa.Integer(), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], ),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.PrimaryKeyConstraint('id_category_place')
    )
    op.create_table('comfort_place',
    sa.Column('id_comfort_place', sa.Integer(), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.Column('id_comfort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comfort'], ['comfort.id_comfort'], ),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.PrimaryKeyConstraint('id_comfort_place')
    )
    op.create_table('finance',
    sa.Column('id_finance', sa.Integer(), nullable=False),
    sa.Column('average_check', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Enum('USD', 'UAH', 'EUR', name='currencyenum'), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.PrimaryKeyConstraint('id_finance')
    )
    op.create_table('payment_method_place',
    sa.Column('id_payment_place', sa.Integer(), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.Column('id_payment_method', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_payment_method'], ['payment_method.id_payment_method'], ),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.PrimaryKeyConstraint('id_payment_place')
    )
    op.create_table('photo',
    sa.Column('id_photo', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.PrimaryKeyConstraint('id_photo')
    )
    op.create_table('time_table_day',
    sa.Column('id_timetable_day', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='dayenum'), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.Column('id_timetable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.ForeignKeyConstraint(['id_timetable'], ['time_table.id_timetable'], ),
    sa.PrimaryKeyConstraint('id_timetable_day')
    )
    op.create_table('translate',
    sa.Column('id_translate', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('RUS', 'ENG', name='languageenum'), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.PrimaryKeyConstraint('id_translate')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('place_user',
    sa.Column('id_place_user', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_place'], ['place.id_place'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_place_user')
    )
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_table('place_user')
    op.drop_table('client')
    op.drop_table('translate')
    op.drop_table('time_table_day')
    op.drop_table('photo')
    op.drop_table('payment_method_place')
    op.drop_table('finance')
    op.drop_table('comfort_place')
    op.drop_table('category_place')
    op.drop_table('time_table')
    op.drop_table('place')
    op.drop_table('payment_method')
    op.drop_table('comfort')
    op.drop_table('category')
    # ### end Alembic commands ###
