"""pointname

Revision ID: 60e14b953af7
Revises: b2e09df59df2
Create Date: 2018-06-11 08:36:53.962684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e14b953af7'
down_revision = 'b2e09df59df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'point', 'route', ['route'], ['id_route'])
    op.create_foreign_key(None, 'route_name', 'language', ['language'], ['id_language'])
    op.create_foreign_key(None, 'route_name', 'route', ['id_route'], ['id_route'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'route_name', type_='foreignkey')
    op.drop_constraint(None, 'route_name', type_='foreignkey')
    op.drop_constraint(None, 'point', type_='foreignkey')
    # ### end Alembic commands ###
