"""v1.0.1

Revision ID: 8c207430e4a1
Revises: 1a1df43e7dd9
Create Date: 2018-03-30 23:30:44.660579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c207430e4a1'
down_revision = '1a1df43e7dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_table', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_table', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
