"""photo

Revision ID: b2e09df59df2
Revises: 73147afad10e
Create Date: 2018-06-09 12:36:11.260773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2e09df59df2'
down_revision = '73147afad10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_name',
    sa.Column('id_route', sa.Integer(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_route'], ['route.id_route'], ),
    sa.ForeignKeyConstraint(['language'], ['language.id_language'], ),
    sa.PrimaryKeyConstraint('id_route', 'language')
    )
    op.create_foreign_key(None, 'point', 'route', ['route'], ['id_route'])
    op.add_column('route', sa.Column('photo_url', sa.String(length=200), nullable=True))
    op.drop_column('route', 'name')
    op.drop_column('route', 'language')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('route', sa.Column('language', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('route', sa.Column('name', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('route', 'photo_url')
    op.drop_constraint(None, 'point', type_='foreignkey')
    op.drop_table('route_name')
    # ### end Alembic commands ###
