"""fix

Revision ID: bb92a633fb5f
Revises: 60e14b953af7
Create Date: 2018-06-11 10:53:46.772714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb92a633fb5f'
down_revision = '60e14b953af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_name',
    sa.Column('id_point', sa.Integer(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.Column('id_route', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_point'], ['point.id_point'], ),
    sa.ForeignKeyConstraint(['id_route'], ['route.id_route'], ),
    sa.ForeignKeyConstraint(['language'], ['language.id_language'], ),
    sa.PrimaryKeyConstraint('id_point', 'language')
    )
    op.drop_column('point', 'route')
    op.drop_column('point', 'title')
    op.create_foreign_key(None, 'route_name', 'route', ['id_route'], ['id_route'])
    op.create_foreign_key(None, 'route_name', 'language', ['language'], ['id_language'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'route_name', type_='foreignkey')
    op.drop_constraint(None, 'route_name', type_='foreignkey')
    op.add_column('point', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('point', sa.Column('route', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('point_name')
    # ### end Alembic commands ###
