"""test db

Revision ID: c62931ff9b4d
Revises: 
Create Date: 2018-04-18 19:08:13.553597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62931ff9b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_name', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('name_l', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('address_l', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('type_establ', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comfort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.Boolean(), nullable=True),
    sa.Column('welcome', sa.Boolean(), nullable=True),
    sa.Column('forChildren', sa.Boolean(), nullable=True),
    sa.Column('animal', sa.Boolean(), nullable=True),
    sa.Column('rentBikes', sa.Boolean(), nullable=True),
    sa.Column('polygraph', sa.Boolean(), nullable=True),
    sa.Column('ramp', sa.Boolean(), nullable=True),
    sa.Column('specialToilet', sa.Boolean(), nullable=True),
    sa.Column('specialService', sa.Boolean(), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit_card', sa.Boolean(), nullable=True),
    sa.Column('credit_card', sa.Boolean(), nullable=True),
    sa.Column('electronic_payment', sa.Boolean(), nullable=True),
    sa.Column('average_check', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=4), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_place'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_place'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_table('time_table')
    op.drop_table('finance')
    op.drop_table('comfort')
    op.drop_table('place')
    op.drop_table('client')
    # ### end Alembic commands ###
